@echo off
echo Starting Attendance System Servers...
echo.
echo Starting Main API Server (Port 3000)...
start cmd /k "cd /d %~dp0 && echo Main API Server && node src\server.js"
timeout /t 2 /nobreak >nul
echo Starting NFC Bridge Server (Port 3001)...
start cmd /k "cd /d %~dp0 && echo NFC Bridge Server && node nfc_bridge_server.js"
echo.
echo Both servers started in separate windows!
echo Press any key to exit this window...
pause >nul